# Site settings
title: 
header-img: img/home-bg.png
email: richardagonzalez@outlook.com
copyright_name: rg1029
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rg1029
learn_profile: rg1029
email_username: richardagonzalez@outlook.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
